In [28]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.io import loadmat
import time

#Loading in the MNIST data
file = loadmat('/Users/samsuidman/Desktop/neurophysics/machine_learning/mnistAll.mat') 

def visualize(X,t,i): #visualizes an image and shows what it is supposed to be 
    print(t[i])
    plt.imshow(X[i][1:].reshape(28,28))

#Preparing the data
train_images = file['mnist']['train_images'][0][0]
train_labels = file['mnist']['train_labels'][0][0].transpose()[0]
test_images = file['mnist']['test_images'][0][0]
test_labels = file['mnist']['test_labels'][0][0].transpose()[0]

X = np.transpose(train_images.reshape(train_images.shape[0]*train_images.shape[1],train_images.shape[2]))
X = X/np.max(X)
#X = np.insert(X,0,1,axis=1) #image data with a one in front 
t = train_labels.copy() #labels for the image data (not needed, only to check)

N = X.shape[0]
K = 10
d = X.shape[1]

def random_pi_mu(d,K):
    pi0 = np.random.random(size=K)
    pi0 = pi0/np.sum(pi0)
    mu0 = np.random.random(size=(K,d))
    k0 = np.random.randin(size=d)
    return k0,pi0,mu0

def get_k(X,mu): #hier komt een lijst van allemaal dezelfde k uit, waarschijnlijk door bepaalde initialisatie. Later kijken of dit fout is. 
    k_matrix = np.matmul(np.log(np.where(mu==0,1,mu)),X.transpose()) + np.matmul(np.log(1-np.where(mu==1,0,mu)),(1-X).transpose()) #Here mu can be 0 since sum of all first digits of image is zero because it is background. In this case x*log(mu) = 0*log(0) = 0. That is why mu should be set to 1 inside the log, so log(1)=0. 
    k = np.argmax(k_matrix,axis=0)
    return k 

def get_pi(k,K,N):
    pi = np.array([len(np.where(k==i)[0]) for i in range(K)])/N
    return pi

def get_mu(pi,d,K):
    mu = np.array([np.sum(X[np.where(k==i)],axis=0)/(pi[i]*N) if pi[i]!=0 else np.zeros(d) for i in range(K)])
    return mu 

def clustering(d,K,N,runs):
    pi,mu = random_pi_mu(d,K)
    for i in range(runs):
        k = get_k(X,mu)
        pi = get_pi(k,K,N)
        mu = get_mu(pi,d,K)
        print(pi)
    return k, pi, mu

#pi0,mu0 = random_pi_mu(d,K)
k,pi,mu = clustering(d,K,N,10)


[8.78833333e-02 3.33333333e-05 1.66766667e-01 3.66666667e-04
 1.66666667e-05 1.25000000e-03 8.00333333e-02 3.22133333e-01
 0.00000000e+00 3.41516667e-01]


/Users/samsuidman/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:35: RuntimeWarning: invalid value encountered in log


[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [81]:
k = get_k(X,mu0)
pi = get_pi(k,K,N)

In [82]:
pi

array([2.70000000e-03, 6.36966667e-01, 5.00000000e-04, 0.00000000e+00,
       1.15866667e-01, 0.00000000e+00, 2.21466667e-01, 2.24333333e-02,
       5.00000000e-05, 1.66666667e-05])

In [84]:
k_matrix = np.matmul(np.log(np.where(mu0==0,1,mu0)),X.transpose()) + np.matmul(np.log(1-np.where(mu0==1,0,mu0)),(1-X).transpose()) 
#k = np.argmax(k_matrix,axis=0)

In [102]:
np.argmax(k_matrix[:,3])

1

In [117]:
np.sum(mu,axis=1)

array([ 98.78558167, 172.78395253, 124.17676215, 142.17085509,
         0.        , 173.50588235, 168.28028155, 160.20196966,
         0.        , 115.67684473])

In [110]:
k_matrix[:,3]

array([-809.95589783, -753.5813319 , -807.61303712, -843.81612966,
       -761.48620738, -807.57878946, -770.05231903, -787.4061799 ,
       -815.61711123, -807.19081035])

In [111]:
k_matrix[:,4]

array([-789.52049486, -755.79070404, -809.09536313, -817.38617704,
       -770.02834955, -809.7411438 , -770.28860003, -750.28093345,
       -811.34436503, -822.16580159])