In [11]:
import numpy as np
a = np.array([[1.0,2,3],[4,5,6],[7,8,9]])
m = 255
c = np.linalg.matrix_power(a,m)
print(c)






[[8.04892137e+306 9.88981878e+306 1.17307162e+307]
 [1.82276316e+307 2.23965380e+307 2.65654444e+307]
 [2.84063418e+307 3.49032572e+307 4.14001725e+307]]
